# -*- coding: utf-8 -*-
"""practical_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ILh-wr61EZxvcSvdAzuCH9D2LtK1E6w7
"""

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

a=[0,1,0,1,1,1,0,0,1,0,0,1]
b=[1,1,0,1,1,1,0,0,0,0,0,1]
matrix=confusion_matrix(a,b)
cl_report=classification_report(a,b)

print("confusion matrix ")
print(matrix)

"""classification report :- evaluation metrics parameter based on actural result and predicted result"""

print(cl_report)
