# -*- coding: utf-8 -*-
"""ml_pract1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a7_RirvfWY4JXM4cVOTeV_75Vu4Z_JUw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df =pd.read_csv("/content/drive/MyDrive/datsets/iris.data.csv");
print(df.info())

df.head(10)

#new_df = df.dropna()
x=df.mean()
df.fillna(x,inplace=True)
df.info()

df.describe()

print(df.duplicated())
print("correaltion")
print(df.corr())

df.plot()

plt.show()

df.plot(kind = 'scatter', x = '5.1', y = '3.5')

df['5.1'].plot(kind='hist')

df['3.5'].plot(kind='hist')
